baseURL = "https://gowind.github.io"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Gowind's site"
theme = "hugo-bearcub"
summaryLength = 15
enableEmoji = true
publishDir = "."

[params]
title = "Gowind's site"
description = "Wannabe electron bender"
keywords = "Govind zig low-level"
favicon = "favicons"
customCss = []
mainSections = ["posts"]
twitterHandle = ["DeepknowledgeU"]

  [params.author]
    email = "mailto:petrovgovind@gmail.com"
    name = "Govind"

generateSocialCard = true

  [params.social]
    twitter = "DeepknowledgeU"
    github = "Gowind"

