baseURL = "https://gowind.github.io"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Gowind's site"
theme = "hugo-bearcub"
summaryLength = 15
enableEmoji = true
publishDir = "public"

[params]
title = "Gowind's site"
description = "Wannabe electron bender"
keywords = "Govind zig low-level"
favicon = "favicons"
customCss = []
mainSections = ["posts"]
twitterHandle = ["DeepknowledgeU"]

  [params.author]
    email = "mailto:petrovgovind@gmail.com"
    name = "Govind"


[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/gowind"

[[params.socialIcons]]
icon = "fa-twitter"
title = "twitter"
url = "https://twitter.com/DeepknowledgeU"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:petrovgovind@gmail.com"

